### ISSUE TITLE
validation.uploaded Error

### ISSUE THREAD

**Issue by antwonw** [LinkStackOrg/Cloudy-Storm#2]
I get a `validation.uploaded` error when attempting to upload this theme, `v1.1`.

<img width="400" alt="Screen Shot 2023-08-10 at 2 10 10 PM" src="https://github.com/LinkStackOrg/Cloudy-Storm/assets/519934/a29a8d3a-6f01-41ed-973a-46f1f915539c">

**Comment by craeckor** [comment]
[Fix](https://github.com/LinkStackOrg/winter-wonderland/issues/4#issuecomment-1868619811)
